name: release-deb

on:
  push:
    tags:
    - '*'

jobs:
  release_build:
      runs-on: ubuntu-latest
      container:
        image: rostooling/setup-ros-docker:ubuntu-bionic-ros-melodic-ros-base-latest
        #options: -u root  # setup-node requires root access
      steps:
      - uses: actions/checkout@v2
        with:
          path: '.'
      - name: Install deps
        run: |
          ls
          echo $ROS_DISTRO
          echo $ROS_PACKAGE_PATH
          #source /opt/ros/melodic/setup.bash
          ls -a /opt/ros/melodic/setup.bash
          rosdep update
          rosdep install --from-path . --ignore-src --rosdistro melodic
          sudo apt install -y python-bloom fakeroot dpkg-dev debhelper
      - name: Build package
        run: |
          ls
          bloom-release  --version
          bloom-generate rosdebian --os-name ubuntu --os-version bionic --ros-distro melodic
          fakeroot debian/rules binary
          cd ..
          ls
